{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_featurestory.TestLogin object at 0x000001E75989DE80>\n\n    @allure.story(\"用户名缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\n\ntest_featurestory.py:25: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1611831535795, "stop": 1611831535796}, {"name": "点击密码", "status": "passed", "start": 1611831535796, "stop": 1611831535796}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"C:\\Users\\narak\\PycharmProjects\\test2\\hogwarts_demo\\python_alluredemo\\test_featurestory.py\", line 25, in test_login_failure\n    assert \"1\" == 1\n"}, "start": 1611831535796, "stop": 1611831535796}], "attachments": [{"name": "stdout", "source": "90e4f3d5-7850-4ae9-8e69-cd8a1a789b75-attachment.txt", "type": "text/plain"}], "start": 1611831535795, "stop": 1611831535796, "uuid": "895e3d4f-d221-4014-80aa-55a0f68a1bab", "historyId": "8d3a93e85f08c77a98c64bb759af7882", "testCaseId": "25838c9f10534eca6a4dd871ce91fdb6", "fullName": "test_featurestory.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "用户名缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_featurestory"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "1804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_featurestory"}]}